version: 0.2
env:
  variables:
    APP_NAME: "angular-aws-devops"
    CACHE_CONTROL: "86400"
    S3_BUCKET: "angular-aws-devops-bucket"
    BUILD_FOLDER: "dist"
    BUILD_ENV: "prod"
phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo installing npm dependancies
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo build process started `date`
      - ng build
  post_build:
    commands:
      - aws s3 cp ${BUILD_FOLDER}/angular-aws-devops s3://${S3_BUCKET} --recursive --acl public-read --cache-control "max-age=${CACHE_CONTROL}"
      - echo Build completed on `date`

